import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';
import vercel from '@astrojs/vercel';

export default defineConfig({
  site: 'https://ebikelocal.com',
  output: 'static',
  adapter: vercel(),
  vite: {
    plugins: [tailwindcss()],
    // Prevent chunk hash mismatches when pre-rendering thousands of pages in parallel
    build: {
      rollupOptions: {
        output: {
          // Keep prerender entry points together — avoids the _shopSlug__<hash>.mjs not found error
          manualChunks: undefined,
        },
      },
    },
  },
  // Limit concurrent page renders to avoid chunk race conditions with 8000+ shop pages
  build: {
    concurrency: 8,
  },
  // Pages that need SSR use `export const prerender = false`
  // Everything else is statically generated by default
});
