/**
 * Seeds the `brands` table with the 15 initial eBike brands.
 * Run: node scripts/seed-brands.mjs
 */
import postgres from 'postgres';
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const envFile = readFileSync(join(__dirname, '..', '.env'), 'utf-8');
const env = Object.fromEntries(
  envFile.split('\n').filter(l => l.includes('=') && !l.startsWith('#'))
    .map(l => { const i = l.indexOf('='); return [l.slice(0, i).trim(), l.slice(i + 1).trim()]; })
);
const sql = postgres(env.DATABASE_URL, { ssl: 'require' });

const brands = [
  {
    name: 'Aventon',
    slug: 'aventon',
    website: 'https://www.aventon.com',
    description: 'Aventon is one of the fastest-growing eBike brands in the US, known for offering high-value bikes with premium components at accessible price points. Their lineup spans commuters, cargo, and fat tire styles.',
    founded_year: 2012,
    headquarters: 'Ontario, CA',
    country_of_origin: 'US',
    price_range_low: 1099,
    price_range_high: 2499,
    affiliate_platform: 'avantlink',
    affiliate_commission_rate: 4.00,
    affiliate_cookie_days: 30,
    dealer_locator_url: 'https://www.aventon.com/pages/electric-bike-shop-dealer-locator',
    estimated_us_dealers: 1800,
  },
  {
    name: 'Lectric eBikes',
    slug: 'lectric',
    website: 'https://www.lectricebikes.com',
    description: 'Lectric eBikes is one of the best-selling eBike brands in America, famous for their affordable folding XP series. Primarily DTC but expanding retail distribution through Best Buy and independent dealers.',
    founded_year: 2019,
    headquarters: 'Phoenix, AZ',
    country_of_origin: 'US',
    price_range_low: 799,
    price_range_high: 1499,
    affiliate_platform: 'avantlink',
    affiliate_commission_rate: 3.00,
    affiliate_cookie_days: 30,
    dealer_locator_url: 'https://www.lectricebikes.com/pages/find-a-retailer',
    estimated_us_dealers: 500,
  },
  {
    name: 'Rad Power Bikes',
    slug: 'rad-power-bikes',
    website: 'https://www.radpowerbikes.com',
    description: 'Rad Power Bikes pioneered the DTC eBike market and once led the US in sales. After filing Chapter 11 in December 2025 and being acquired by Life EV, their dealer network status is in transition.',
    founded_year: 2007,
    headquarters: 'Seattle, WA',
    country_of_origin: 'US',
    price_range_low: 1099,
    price_range_high: 1999,
    affiliate_platform: 'avantlink',
    affiliate_commission_rate: 5.00,
    affiliate_cookie_days: 30,
    dealer_locator_url: 'https://www.radpowerbikes.com/pages/locations',
    estimated_us_dealers: 1200,
    is_active: true,
  },
  {
    name: 'Velotric',
    slug: 'velotric',
    website: 'https://www.velotricbike.com',
    description: 'Velotric is a rapidly growing eBike brand known for high-quality components and sleek designs. They offer one of the best affiliate programs in the industry with 7% commission and monthly bonuses.',
    founded_year: 2021,
    headquarters: 'San Jose, CA',
    country_of_origin: 'US',
    price_range_low: 999,
    price_range_high: 2299,
    affiliate_platform: 'impact',
    affiliate_commission_rate: 7.00,
    affiliate_cookie_days: 30,
    dealer_locator_url: 'https://www.velotricbike.com/pages/find-a-dealer',
    estimated_us_dealers: 1200,
  },
  {
    name: 'Pedego',
    slug: 'pedego',
    website: 'https://www.pedegoelectricbikes.com',
    description: 'Pedego operates the largest branded eBike retail franchise in the US with 200+ company-owned stores. Known for comfortable cruiser-style bikes and exceptional in-store experience.',
    founded_year: 2008,
    headquarters: 'Fountain Valley, CA',
    country_of_origin: 'US',
    price_range_low: 1595,
    price_range_high: 5295,
    affiliate_platform: 'direct',
    affiliate_commission_rate: null,
    affiliate_cookie_days: null,
    dealer_locator_url: 'https://dealers.pedegoelectricbikes.com',
    estimated_us_dealers: 200,
  },
  {
    name: 'Trek',
    slug: 'trek',
    website: 'https://www.trekbikes.com',
    description: 'Trek is one of the world\'s largest bicycle manufacturers, offering a premium lineup of electric bikes under the Powerfly (mountain) and FX (commuter) lines. Their 1,500+ dealer network is the largest of any brand we track.',
    founded_year: 1976,
    headquarters: 'Waterloo, WI',
    country_of_origin: 'US',
    price_range_low: 1599,
    price_range_high: 12999,
    affiliate_platform: null,
    affiliate_commission_rate: null,
    affiliate_cookie_days: null,
    dealer_locator_url: 'https://www.trekbikes.com/us/en_US/store-finder/',
    estimated_us_dealers: 1700,
  },
  {
    name: 'Specialized',
    slug: 'specialized',
    website: 'https://www.specialized.com',
    description: 'Specialized is a premier bicycle brand with one of the most respected eBike lineups, including the Turbo Levo (mountain) and Turbo Como (commuter). Their Specialized Turbo series is renowned for performance and quality.',
    founded_year: 1974,
    headquarters: 'Morgan Hill, CA',
    country_of_origin: 'US',
    price_range_low: 3000,
    price_range_high: 15000,
    affiliate_platform: null,
    affiliate_commission_rate: null,
    affiliate_cookie_days: null,
    dealer_locator_url: 'https://www.specialized.com/us/en/store-finder',
    estimated_us_dealers: 1500,
  },
  {
    name: 'Giant',
    slug: 'giant',
    website: 'https://www.giant-bicycles.com',
    description: 'Giant is the world\'s largest bicycle manufacturer by volume, offering a wide range of electric bikes across all categories. Their E+ series covers mountain, road, and urban riding.',
    founded_year: 1972,
    headquarters: 'Taichung, Taiwan',
    country_of_origin: 'Taiwan',
    price_range_low: 1500,
    price_range_high: 8000,
    affiliate_platform: null,
    affiliate_commission_rate: null,
    affiliate_cookie_days: null,
    dealer_locator_url: 'https://www.giant-bicycles.com/us/stores',
    estimated_us_dealers: 1224,
  },
  {
    name: 'Cannondale',
    slug: 'cannondale',
    website: 'https://www.cannondale.com',
    description: 'Cannondale is a premium American bicycle brand offering electric models in their Topstone (gravel), Habit (mountain), and Mavaro (urban) lines. Their Locally.com integration provides real-time inventory data at dealerships.',
    founded_year: 1971,
    headquarters: 'Wilton, CT',
    country_of_origin: 'US',
    price_range_low: 2500,
    price_range_high: 9000,
    affiliate_platform: null,
    affiliate_commission_rate: null,
    affiliate_cookie_days: null,
    dealer_locator_url: 'https://www.cannondale.com/en-us/find-a-dealer',
    estimated_us_dealers: 1000,
  },
  {
    name: 'Himiway',
    slug: 'himiway',
    website: 'https://www.himiwaybike.com',
    description: 'Himiway specializes in powerful fat tire eBikes for off-road and adventure riding. Their bikes are known for long range and robust construction at competitive prices.',
    founded_year: 2017,
    headquarters: 'Los Angeles, CA',
    country_of_origin: 'China',
    price_range_low: 999,
    price_range_high: 2499,
    affiliate_platform: 'shareasale',
    affiliate_commission_rate: 7.50,
    affiliate_cookie_days: 7,
    dealer_locator_url: null,
    estimated_us_dealers: 50,
  },
  {
    name: 'Ride1UP',
    slug: 'ride1up',
    website: 'https://www.ride1up.com',
    description: 'Ride1UP is a popular DTC eBike brand known for offering feature-rich bikes at competitive prices. Their Core-5 and 500 Series are among the best-reviewed budget commuter eBikes.',
    founded_year: 2018,
    headquarters: 'San Diego, CA',
    country_of_origin: 'US',
    price_range_low: 1045,
    price_range_high: 2495,
    affiliate_platform: 'direct',
    affiliate_commission_rate: 5.00,
    affiliate_cookie_days: 30,
    dealer_locator_url: null,
    estimated_us_dealers: 20,
  },
  {
    name: 'EVELO',
    slug: 'evelo',
    website: 'https://www.evelo.com',
    description: 'EVELO focuses on premium mid-drive eBikes designed for older and less experienced riders. Their bikes feature automatic transmissions and are marketed heavily to the 55+ demographic.',
    founded_year: 2012,
    headquarters: 'Seattle, WA',
    country_of_origin: 'US',
    price_range_low: 2999,
    price_range_high: 5499,
    affiliate_platform: 'avantlink',
    affiliate_commission_rate: 6.00,
    affiliate_cookie_days: 30,
    dealer_locator_url: null,
    estimated_us_dealers: 30,
  },
  {
    name: 'QuietKat',
    slug: 'quietkat',
    website: 'https://www.quietkat.com',
    description: 'QuietKat specializes in hunting and off-road utility eBikes with high payload capacity and camouflage options. A niche leader in the hunting eBike segment.',
    founded_year: 2012,
    headquarters: 'Eagle, CO',
    country_of_origin: 'US',
    price_range_low: 1999,
    price_range_high: 5249,
    affiliate_platform: 'avantlink',
    affiliate_commission_rate: 5.00,
    affiliate_cookie_days: 30,
    dealer_locator_url: null,
    estimated_us_dealers: 100,
  },
  {
    name: 'Tern',
    slug: 'tern',
    website: 'https://www.ternbicycles.com',
    description: 'Tern makes premium folding and cargo eBikes engineered for urban living. Their GSD cargo bike and Vektron folding bike are benchmark products in their categories.',
    founded_year: 2011,
    headquarters: 'Taipei, Taiwan',
    country_of_origin: 'Taiwan',
    price_range_low: 1799,
    price_range_high: 5999,
    affiliate_platform: null,
    affiliate_commission_rate: null,
    affiliate_cookie_days: null,
    dealer_locator_url: 'https://www.ternbicycles.com/us/dealers/map',
    estimated_us_dealers: 150,
  },
  {
    name: 'Gazelle',
    slug: 'gazelle',
    website: 'https://www.gazellebikes.com',
    description: 'Gazelle is a Dutch bicycle heritage brand with over 130 years of history, offering premium step-through and city eBikes. Known for exceptional build quality and comfort.',
    founded_year: 1892,
    headquarters: 'Dieren, Netherlands',
    country_of_origin: 'Netherlands',
    price_range_low: 2999,
    price_range_high: 5499,
    affiliate_platform: null,
    affiliate_commission_rate: null,
    affiliate_cookie_days: null,
    dealer_locator_url: 'https://www.gazellebikes.com/en-us/find-a-dealer',
    estimated_us_dealers: 70,
  },
];

console.log(`Seeding ${brands.length} brands...`);
let count = 0;
for (const brand of brands) {
  try {
    await sql`
      INSERT INTO brands (
        name, slug, website, description, founded_year, headquarters,
        country_of_origin, price_range_low, price_range_high,
        affiliate_platform, affiliate_commission_rate, affiliate_cookie_days,
        dealer_locator_url, estimated_us_dealers, is_active
      ) VALUES (
        ${brand.name}, ${brand.slug}, ${brand.website || null},
        ${brand.description || null}, ${brand.founded_year || null},
        ${brand.headquarters || null}, ${brand.country_of_origin || null},
        ${brand.price_range_low || null}, ${brand.price_range_high || null},
        ${brand.affiliate_platform || null}, ${brand.affiliate_commission_rate || null},
        ${brand.affiliate_cookie_days || null}, ${brand.dealer_locator_url || null},
        ${brand.estimated_us_dealers || null}, ${brand.is_active ?? true}
      )
      ON CONFLICT (slug) DO UPDATE SET
        name = EXCLUDED.name,
        website = EXCLUDED.website,
        description = EXCLUDED.description,
        founded_year = EXCLUDED.founded_year,
        headquarters = EXCLUDED.headquarters,
        country_of_origin = EXCLUDED.country_of_origin,
        price_range_low = EXCLUDED.price_range_low,
        price_range_high = EXCLUDED.price_range_high,
        affiliate_platform = EXCLUDED.affiliate_platform,
        affiliate_commission_rate = EXCLUDED.affiliate_commission_rate,
        affiliate_cookie_days = EXCLUDED.affiliate_cookie_days,
        dealer_locator_url = EXCLUDED.dealer_locator_url,
        estimated_us_dealers = EXCLUDED.estimated_us_dealers
    `;
    console.log(`✓ ${brand.name}`);
    count++;
  } catch (err) {
    console.error(`✗ ${brand.name}: ${err.message}`);
  }
}

console.log(`\nSeeded ${count} brands.`);
await sql.end();
