/**
 * Seeds the `bikes` table with top models per brand.
 * MVP target: 5–10 models × 15 brands = ~100 bikes
 *
 * Run: node scripts/seed-bikes.mjs
 *
 * Specs are accurate for 2025/2026 model years.
 * hero_image_url intentionally left null — will be populated
 * from brand press kits or product pages in a later pass.
 */
import postgres from 'postgres';
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const envFile = readFileSync(join(__dirname, '..', '.env'), 'utf-8');
const env = Object.fromEntries(
  envFile.split('\n').filter(l => l.includes('=') && !l.startsWith('#'))
    .map(l => { const i = l.indexOf('='); return [l.slice(0, i).trim(), l.slice(i + 1).trim()]; })
);
const sql = postgres(env.DATABASE_URL, { ssl: 'require' });

function toSlug(str) {
  return str.toLowerCase().replace(/[^a-z0-9\s-]/g, '').replace(/\s+/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
}

// Load brand IDs by slug
const brandsRaw = await sql`SELECT id, slug FROM brands`;
const BRANDS = Object.fromEntries(brandsRaw.map(b => [b.slug, b.id]));

const bikes = [

  // ── AVENTON ───────────────────────────────────────────────────────────────
  {
    brand: 'aventon',
    model_name: 'Pace 500.3',
    year: 2025,
    msrp: 1199,
    category: 'commuter',
    ebike_class: 2,
    motor_watts: 500,
    motor_type: 'rear hub',
    motor_torque_nm: 55,
    battery_wh: 614,
    range_miles_low: 40,
    range_miles_high: 60,
    top_speed_mph: 28,
    charge_time_hours: 4.5,
    weight_lbs: 49,
    max_payload_lbs: 300,
    wheel_size: '700c',
    frame_material: 'aluminum',
    gearing: '7-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'none',
    has_throttle: true,
    has_torque_sensor: false,
    has_app: true,
    has_removable_battery: true,
    key_features: ['Integrated LED display', 'USB-C charging', 'Walk mode', 'Automatic brake light'],
    pros: ['Excellent value for price', 'Hydraulic brakes standard', 'Good range', 'Large dealer network'],
    cons: ['Cadence sensor only (no torque)', 'Heavier than premium commuters', 'App connectivity can be buggy'],
    best_for: 'Budget-conscious commuters who want reliable daily transportation',
    expert_rating: 8.5,
    affiliate_url: 'https://www.aventon.com/products/aventon-pace-500-3-step-through-ebike',
  },
  {
    brand: 'aventon',
    model_name: 'Level.2',
    year: 2025,
    msrp: 1499,
    category: 'commuter',
    ebike_class: 2,
    motor_watts: 500,
    motor_type: 'rear hub',
    motor_torque_nm: 60,
    battery_wh: 720,
    range_miles_low: 45,
    range_miles_high: 70,
    top_speed_mph: 28,
    charge_time_hours: 5.0,
    weight_lbs: 52,
    max_payload_lbs: 300,
    wheel_size: '700c',
    frame_material: 'aluminum',
    gearing: '8-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'front fork',
    has_throttle: true,
    has_torque_sensor: true,
    has_app: true,
    has_removable_battery: true,
    key_features: ['Torque sensor pedal assist', 'Integrated rear rack', 'Front suspension', 'Color display'],
    pros: ['Torque sensor for natural feel', 'Longer range than Pace', 'Front suspension adds comfort', 'Integrated lighting'],
    cons: ['Heavier with rack', 'Price jump over Pace 500', 'Suspension non-lockout'],
    best_for: 'Commuters wanting a more natural pedaling feel with cargo capability',
    expert_rating: 9.0,
    affiliate_url: 'https://www.aventon.com/products/aventon-level-2-ebike',
  },
  {
    brand: 'aventon',
    model_name: 'Aventure.2',
    year: 2025,
    msrp: 1799,
    category: 'fat-tire',
    ebike_class: 2,
    motor_watts: 750,
    motor_type: 'rear hub',
    motor_torque_nm: 80,
    battery_wh: 720,
    range_miles_low: 35,
    range_miles_high: 60,
    top_speed_mph: 28,
    charge_time_hours: 5.5,
    weight_lbs: 70,
    max_payload_lbs: 400,
    wheel_size: '26"',
    frame_material: 'aluminum',
    frame_types: ['step-over', 'step-through'],
    gearing: '8-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'front fork',
    has_throttle: true,
    has_torque_sensor: false,
    has_app: true,
    has_removable_battery: true,
    key_features: ['4" fat tires', '750W motor', 'High payload capacity', 'LED headlight'],
    pros: ['Handles sand, snow, gravel', 'Powerful motor', 'High weight capacity', 'Fun ride'],
    cons: ['Heavy at 70 lbs', 'Cadence sensor only', 'Higher rolling resistance on pavement'],
    best_for: 'Riders who want an all-terrain bike for beach, trail, and winter riding',
    expert_rating: 8.3,
    affiliate_url: 'https://www.aventon.com/products/aventon-aventure-2-fat-tire-ebike',
  },
  {
    brand: 'aventon',
    model_name: 'Abound',
    year: 2025,
    msrp: 1999,
    category: 'cargo',
    ebike_class: 2,
    motor_watts: 750,
    motor_type: 'rear hub',
    motor_torque_nm: 80,
    battery_wh: 720,
    range_miles_low: 30,
    range_miles_high: 60,
    top_speed_mph: 20,
    charge_time_hours: 5.5,
    weight_lbs: 77,
    max_payload_lbs: 400,
    wheel_size: '20"',
    frame_material: 'aluminum',
    gearing: '7-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'none',
    has_throttle: true,
    has_torque_sensor: false,
    has_app: true,
    has_removable_battery: true,
    key_features: ['Longtail cargo design', 'Dual child seat compatible', 'Integrated rear deck', '400 lb payload'],
    pros: ['Affordable cargo eBike', 'High payload', 'Easy mounting for kids', 'Good dealer support'],
    cons: ['Heavy', 'No torque sensor', 'Less nimble than smaller bikes'],
    best_for: 'Parents replacing a second car for school runs and errands',
    expert_rating: 8.2,
    affiliate_url: 'https://www.aventon.com/products/aventon-abound-cargo-ebike',
  },
  {
    brand: 'aventon',
    model_name: 'Soltera.2',
    year: 2025,
    msrp: 1099,
    category: 'commuter',
    ebike_class: 3,
    motor_watts: 350,
    motor_type: 'rear hub',
    motor_torque_nm: 40,
    battery_wh: 375,
    range_miles_low: 25,
    range_miles_high: 45,
    top_speed_mph: 28,
    charge_time_hours: 3.5,
    weight_lbs: 38,
    max_payload_lbs: 275,
    wheel_size: '700c',
    frame_material: 'aluminum',
    gearing: 'single-speed',
    brakes: 'mechanical disc',
    suspension: 'none',
    has_throttle: false,
    has_torque_sensor: false,
    has_app: false,
    has_removable_battery: true,
    key_features: ['Lightweight at 38 lbs', 'Single-speed simplicity', 'Slim battery integration', 'Class 3 speed'],
    pros: ['Lightest Aventon model', 'Low maintenance single-speed', 'Good for flat terrain', 'Affordable entry point'],
    cons: ['Short range', 'No throttle', 'Not ideal for hills', 'No suspension'],
    best_for: 'Urban riders on flat terrain who prioritize weight and simplicity',
    expert_rating: 7.8,
    affiliate_url: 'https://www.aventon.com/products/soltera-2-ebike',
  },

  // ── LECTRIC ───────────────────────────────────────────────────────────────
  {
    brand: 'lectric',
    model_name: 'XP 3.0',
    year: 2025,
    msrp: 999,
    category: 'folding',
    ebike_class: 2,
    motor_watts: 500,
    motor_type: 'rear hub',
    motor_torque_nm: 55,
    battery_wh: 518,
    range_miles_low: 45,
    range_miles_high: 65,
    top_speed_mph: 28,
    charge_time_hours: 4.5,
    weight_lbs: 64,
    max_payload_lbs: 330,
    wheel_size: '20"',
    frame_material: 'aluminum',
    gearing: '7-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'front fork',
    has_throttle: true,
    has_torque_sensor: false,
    has_app: false,
    has_removable_battery: true,
    key_features: ['Folds in seconds', 'Best-selling US eBike', 'Front suspension', 'Hydraulic brakes at this price'],
    pros: ['Incredible value', 'Compact storage', 'Hydraulic disc brakes', 'Great for first-time buyers'],
    cons: ['Heavy for a folder', 'Cadence sensor only', 'No app', 'Slower folding mechanism'],
    best_for: 'First-time eBike buyers, apartment dwellers, and multimodal commuters',
    expert_rating: 9.2,
    affiliate_url: 'https://lectricebikes.com/products/lectric-xp-3',
  },
  {
    brand: 'lectric',
    model_name: 'XPeak',
    year: 2025,
    msrp: 1299,
    category: 'fat-tire',
    ebike_class: 2,
    motor_watts: 500,
    motor_type: 'rear hub',
    motor_torque_nm: 60,
    battery_wh: 576,
    range_miles_low: 40,
    range_miles_high: 65,
    top_speed_mph: 28,
    charge_time_hours: 5.0,
    weight_lbs: 69,
    max_payload_lbs: 330,
    wheel_size: '20"',
    frame_material: 'aluminum',
    gearing: '7-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'front fork',
    has_throttle: true,
    has_torque_sensor: false,
    has_app: false,
    has_removable_battery: true,
    key_features: ['4" fat tires', 'Foldable frame', 'Full-color display', 'All-terrain capability'],
    pros: ['Fat tires plus folding is rare', 'Great value', 'Versatile all-terrain use', 'Hydraulic brakes'],
    cons: ['Very heavy', 'No torque sensor', 'Bulky when folded', 'Limited color options'],
    best_for: 'Riders who want fat-tire versatility with compact storage',
    expert_rating: 8.6,
    affiliate_url: 'https://lectricebikes.com/products/lectric-xpeak',
  },
  {
    brand: 'lectric',
    model_name: 'XPress',
    year: 2025,
    msrp: 1499,
    category: 'cargo',
    ebike_class: 2,
    motor_watts: 500,
    motor_type: 'rear hub',
    motor_torque_nm: 55,
    battery_wh: 518,
    range_miles_low: 40,
    range_miles_high: 60,
    top_speed_mph: 20,
    charge_time_hours: 4.5,
    weight_lbs: 73,
    max_payload_lbs: 450,
    wheel_size: '20"',
    frame_material: 'aluminum',
    gearing: '7-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'none',
    has_throttle: true,
    has_torque_sensor: false,
    has_app: false,
    has_removable_battery: true,
    key_features: ['450 lb payload capacity', 'Longtail design', 'Pannier-compatible rack', 'Foldable'],
    pros: ['Highest payload in class', 'Affordable cargo option', 'Folds for storage', 'Strong motor'],
    cons: ['Heavy', 'No suspension', 'Class 2 speed limit', 'Cadence sensor'],
    best_for: 'Budget-focused cargo haulers and small business last-mile delivery',
    expert_rating: 8.4,
    affiliate_url: 'https://lectricebikes.com/products/lectric-xpress',
  },
  {
    brand: 'lectric',
    model_name: 'ONE',
    year: 2025,
    msrp: 1799,
    category: 'commuter',
    ebike_class: 3,
    motor_watts: 500,
    motor_type: 'rear hub',
    motor_torque_nm: 60,
    battery_wh: 614,
    range_miles_low: 50,
    range_miles_high: 80,
    top_speed_mph: 28,
    charge_time_hours: 4.5,
    weight_lbs: 44,
    max_payload_lbs: 330,
    wheel_size: '700c',
    frame_material: 'aluminum',
    gearing: 'Enviolo stepless CVT',
    brakes: 'hydraulic disc',
    suspension: 'front fork',
    has_throttle: true,
    has_torque_sensor: true,
    has_app: true,
    has_removable_battery: true,
    key_features: ['Torque sensor', 'Enviolo CVT auto-shift', 'Integrated lights', 'App connectivity'],
    pros: ['Premium feel at mid-range price', 'Auto-shifting transmission', 'Torque sensor', 'Long range'],
    cons: ['Highest Lectric price point', 'CVT adds complexity', 'Heavier than pure commuters'],
    best_for: 'Commuters upgrading from an XP who want a premium daily driver',
    expert_rating: 9.0,
    affiliate_url: 'https://lectricebikes.com/products/lectric-one',
  },

  // ── RAD POWER BIKES ───────────────────────────────────────────────────────
  {
    brand: 'rad-power-bikes',
    model_name: 'RadRunner 3 Plus',
    year: 2025,
    msrp: 1699,
    category: 'cruiser',
    ebike_class: 2,
    motor_watts: 750,
    motor_type: 'rear hub',
    motor_torque_nm: 80,
    battery_wh: 672,
    range_miles_low: 25,
    range_miles_high: 45,
    top_speed_mph: 20,
    charge_time_hours: 6.0,
    weight_lbs: 65,
    max_payload_lbs: 300,
    wheel_size: '20"',
    frame_material: 'aluminum',
    gearing: '7-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'none',
    has_throttle: true,
    has_torque_sensor: false,
    has_app: true,
    has_removable_battery: true,
    key_features: ['Utility/moped style', 'Rear passenger seat compatible', 'Wide tires', 'Integrated rack'],
    pros: ['Versatile moped-style design', 'Strong motor', 'Great for hauling', 'Large community'],
    cons: ['Heavy', 'Short range', 'No suspension', 'Uncertain brand future (bankruptcy/acquisition)'],
    best_for: 'Utility riders who want a moped-style eBike for errands and short trips',
    expert_rating: 8.0,
    affiliate_url: 'https://www.radpowerbikes.com/products/radrunner-3-plus',
  },
  {
    brand: 'rad-power-bikes',
    model_name: 'RadCity 5 Plus',
    year: 2025,
    msrp: 1799,
    category: 'commuter',
    ebike_class: 2,
    motor_watts: 750,
    motor_type: 'rear hub',
    motor_torque_nm: 80,
    battery_wh: 672,
    range_miles_low: 25,
    range_miles_high: 50,
    top_speed_mph: 20,
    charge_time_hours: 6.0,
    weight_lbs: 62,
    max_payload_lbs: 275,
    wheel_size: '700c',
    frame_material: 'aluminum',
    frame_types: ['step-over', 'step-through'],
    gearing: '8-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'front fork',
    has_throttle: true,
    has_torque_sensor: false,
    has_app: true,
    has_removable_battery: true,
    key_features: ['Front suspension', 'Integrated fenders', 'Rear rack included', 'Bright headlight'],
    pros: ['Complete commuter package out of box', 'Front suspension', 'Reputable brand history', 'Wide availability'],
    cons: ['Heavy', 'Class 2 only', 'No torque sensor', 'Brand uncertainty post-acquisition'],
    best_for: 'Commuters wanting a complete, ready-to-ride setup without accessories shopping',
    expert_rating: 8.1,
    affiliate_url: 'https://www.radpowerbikes.com/products/radcity-5-plus',
  },
  {
    brand: 'rad-power-bikes',
    model_name: 'RadWagon 4',
    year: 2025,
    msrp: 1999,
    category: 'cargo',
    ebike_class: 2,
    motor_watts: 750,
    motor_type: 'rear hub',
    motor_torque_nm: 80,
    battery_wh: 672,
    range_miles_low: 20,
    range_miles_high: 45,
    top_speed_mph: 20,
    charge_time_hours: 6.0,
    weight_lbs: 77,
    max_payload_lbs: 350,
    wheel_size: '22"',
    frame_material: 'aluminum',
    gearing: '7-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'none',
    has_throttle: true,
    has_torque_sensor: false,
    has_app: true,
    has_removable_battery: true,
    key_features: ['10-foot deck length', 'Dual child seats compatible', 'Side panels available', 'Massive cargo capacity'],
    pros: ['Car replacement capability', 'Wide ecosystem of accessories', 'Strong brand community', 'Proven platform'],
    cons: ['Very heavy', 'Short range fully loaded', 'No torque sensor', 'Brand acquisition uncertainty'],
    best_for: 'Families replacing a second car for school and grocery runs',
    expert_rating: 8.5,
    affiliate_url: 'https://www.radpowerbikes.com/products/radwagon-4',
  },
  {
    brand: 'rad-power-bikes',
    model_name: 'RadRover 6 Plus',
    year: 2025,
    msrp: 1999,
    category: 'fat-tire',
    ebike_class: 2,
    motor_watts: 750,
    motor_type: 'rear hub',
    motor_torque_nm: 80,
    battery_wh: 672,
    range_miles_low: 25,
    range_miles_high: 45,
    top_speed_mph: 20,
    charge_time_hours: 6.0,
    weight_lbs: 73,
    max_payload_lbs: 275,
    wheel_size: '26"',
    frame_material: 'aluminum',
    frame_types: ['step-over', 'step-through'],
    gearing: '7-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'front fork',
    has_throttle: true,
    has_torque_sensor: false,
    has_app: true,
    has_removable_battery: true,
    key_features: ['4" Kenda fat tires', 'Front suspension fork', 'Color display', 'Integrated lighting system'],
    pros: ['Popular and proven model', 'Good off-road capability', 'Large accessories ecosystem', 'Front suspension'],
    cons: ['Heavy', 'Class 2 speed cap', 'Cadence sensor only', 'Brand uncertainty'],
    best_for: 'Casual off-road riders and beach cruisers who want a go-anywhere eBike',
    expert_rating: 8.2,
    affiliate_url: 'https://www.radpowerbikes.com/products/radrover-6-plus',
  },

  // ── VELOTRIC ─────────────────────────────────────────────────────────────
  {
    brand: 'velotric',
    model_name: 'Discover 1',
    year: 2025,
    msrp: 999,
    category: 'commuter',
    ebike_class: 3,
    motor_watts: 500,
    motor_type: 'rear hub',
    motor_torque_nm: 55,
    battery_wh: 480,
    range_miles_low: 40,
    range_miles_high: 65,
    top_speed_mph: 28,
    charge_time_hours: 4.0,
    weight_lbs: 49,
    max_payload_lbs: 265,
    wheel_size: '700c',
    frame_material: 'aluminum',
    gearing: '7-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'none',
    has_throttle: true,
    has_torque_sensor: true,
    has_app: true,
    has_removable_battery: true,
    key_features: ['Torque sensor at $999', 'IPX6 waterproof rating', 'Bluetooth app', 'Lightweight build'],
    pros: ['Best-in-class torque sensor at this price', 'Waterproof rating', 'Natural pedal feel', 'Good range'],
    cons: ['No suspension', 'Lower payload than some competitors', 'Newer brand (less dealer support)', 'Smaller community'],
    best_for: 'Value seekers who refuse to sacrifice ride feel — best torque sensor under $1,000',
    expert_rating: 9.3,
    affiliate_url: 'https://velotricbike.com/products/discover-1-ebike',
  },
  {
    brand: 'velotric',
    model_name: 'Nomad 1',
    year: 2025,
    msrp: 1499,
    category: 'fat-tire',
    ebike_class: 2,
    motor_watts: 750,
    motor_type: 'rear hub',
    motor_torque_nm: 80,
    battery_wh: 692,
    range_miles_low: 40,
    range_miles_high: 65,
    top_speed_mph: 25,
    charge_time_hours: 5.5,
    weight_lbs: 70,
    max_payload_lbs: 440,
    wheel_size: '26"',
    frame_material: 'aluminum',
    gearing: '7-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'front fork',
    has_throttle: true,
    has_torque_sensor: true,
    has_app: true,
    has_removable_battery: true,
    key_features: ['440 lb payload', 'Torque sensor on fat tire', 'IPX6 waterproof', '750W motor'],
    pros: ['Highest payload in fat-tire class', 'Torque sensor is rare here', 'Great all-terrain performance', 'Waterproof'],
    cons: ['Heavy', 'Speed limited to 25mph', 'Newer brand', 'Less dealer presence'],
    best_for: 'Larger riders or those who want maximum versatility in a fat-tire eBike',
    expert_rating: 9.0,
    affiliate_url: 'https://velotricbike.com/products/nomad-1',
  },
  {
    brand: 'velotric',
    model_name: 'T1 ST',
    year: 2025,
    msrp: 1699,
    category: 'commuter',
    ebike_class: 3,
    motor_watts: 500,
    motor_type: 'rear hub',
    motor_torque_nm: 60,
    battery_wh: 692,
    range_miles_low: 50,
    range_miles_high: 80,
    top_speed_mph: 28,
    charge_time_hours: 5.0,
    weight_lbs: 52,
    max_payload_lbs: 300,
    wheel_size: '700c',
    frame_material: 'aluminum',
    gearing: '8-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'front fork',
    has_throttle: true,
    has_torque_sensor: true,
    has_app: true,
    has_removable_battery: true,
    key_features: ['80-mile max range', 'Torque sensor', 'Front suspension', 'Large battery'],
    pros: ['Best range in Velotric lineup', 'Torque sensor standard', 'Comfortable front suspension', 'Long-distance capable'],
    cons: ['Heavier than Discover 1', 'Higher price', 'Less dealer presence', 'Suspension is entry-level'],
    best_for: 'Long-distance commuters who need 50+ miles of reliable daily range',
    expert_rating: 8.8,
    affiliate_url: 'https://velotricbike.com/products/t1-st-ebike',
  },

  // ── PEDEGO ───────────────────────────────────────────────────────────────
  {
    brand: 'pedego',
    model_name: 'Interceptor',
    year: 2025,
    msrp: 3295,
    category: 'cruiser',
    ebike_class: 2,
    motor_watts: 500,
    motor_type: 'rear hub',
    motor_torque_nm: 55,
    battery_wh: 576,
    range_miles_low: 15,
    range_miles_high: 30,
    top_speed_mph: 20,
    charge_time_hours: 4.5,
    weight_lbs: 62,
    max_payload_lbs: 275,
    wheel_size: '26"',
    frame_material: 'aluminum',
    gearing: '7-speed Shimano',
    brakes: 'mechanical disc',
    suspension: 'front fork',
    has_throttle: true,
    has_torque_sensor: false,
    has_app: false,
    has_removable_battery: true,
    key_features: ['Beach cruiser design', 'Wide handlebars', 'Cushioned saddle', 'Dedicated Pedego stores'],
    pros: ['Best-in-class comfort', 'Dedicated retail stores with service', 'Iconic design', 'Strong dealer network'],
    cons: ['Very expensive for specs', 'Short range', 'No torque sensor', 'Heavy for a cruiser'],
    best_for: 'Comfort-focused riders who value in-person service and iconic beach cruiser styling',
    expert_rating: 7.5,
    affiliate_url: 'https://www.pedegoelectricbikes.com/bikes/interceptor/',
  },
  {
    brand: 'pedego',
    model_name: 'City Commuter',
    year: 2025,
    msrp: 2795,
    category: 'commuter',
    ebike_class: 2,
    motor_watts: 500,
    motor_type: 'rear hub',
    motor_torque_nm: 55,
    battery_wh: 576,
    range_miles_low: 20,
    range_miles_high: 40,
    top_speed_mph: 20,
    charge_time_hours: 4.5,
    weight_lbs: 55,
    max_payload_lbs: 275,
    wheel_size: '700c',
    frame_material: 'aluminum',
    frame_types: ['step-over', 'step-through'],
    gearing: '8-speed Shimano',
    brakes: 'mechanical disc',
    suspension: 'front fork',
    has_throttle: true,
    has_torque_sensor: false,
    has_app: false,
    has_removable_battery: true,
    key_features: ['Upright comfort geometry', 'Integrated rack and fenders', 'Franchise store support', 'Step-through option'],
    pros: ['Premium in-store experience', 'Complete commuter package', 'Lifetime warranty on frame', 'Strong resale value'],
    cons: ['Overpriced for specs vs. competitors', 'Class 2 only', 'No torque sensor', 'Smaller online community'],
    best_for: 'Riders who prefer buying from a dedicated eBike store with full service support',
    expert_rating: 7.8,
    affiliate_url: 'https://www.pedegoelectricbikes.com/bikes/city-commuter/',
  },

  // ── TREK ─────────────────────────────────────────────────────────────────
  {
    brand: 'trek',
    model_name: 'Verve+ 2',
    year: 2025,
    msrp: 2399,
    category: 'commuter',
    ebike_class: 3,
    motor_watts: 250,
    motor_type: 'mid-drive',
    motor_torque_nm: 50,
    battery_wh: 500,
    range_miles_low: 35,
    range_miles_high: 65,
    top_speed_mph: 28,
    charge_time_hours: 4.5,
    weight_lbs: 46,
    max_payload_lbs: 300,
    wheel_size: '700c',
    frame_material: 'aluminum',
    frame_types: ['step-over', 'lowstep'],
    gearing: '9-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'none',
    has_throttle: false,
    has_torque_sensor: true,
    has_app: true,
    has_removable_battery: true,
    key_features: ['Bosch Active Line Plus motor', 'Kiox 300 display', 'Integrated lighting', 'Fender and rack ready'],
    pros: ['Bosch motor reliability', 'Natural mid-drive feel', 'Lightweight for a commuter', 'Huge dealer network'],
    cons: ['No throttle', 'Higher price for motor wattage', 'Bosch ecosystem lock-in', 'Less acceleration punch'],
    best_for: 'Everyday commuters who want the reliability of a major bike brand with dealer support nationwide',
    expert_rating: 8.7,
    affiliate_url: 'https://www.trekbikes.com/us/en_US/bikes/electric-bikes/electric-fitness-bikes/verve/verve-2-equipped-lowstep/',
  },
  {
    brand: 'trek',
    model_name: 'Allant+ 7',
    year: 2025,
    msrp: 3799,
    category: 'commuter',
    ebike_class: 3,
    motor_watts: 250,
    motor_type: 'mid-drive',
    motor_torque_nm: 65,
    battery_wh: 625,
    range_miles_low: 45,
    range_miles_high: 90,
    top_speed_mph: 28,
    charge_time_hours: 5.5,
    weight_lbs: 51,
    max_payload_lbs: 300,
    wheel_size: '700c',
    frame_material: 'aluminum',
    frame_types: ['step-over', 'lowstep'],
    gearing: 'Enviolo CVT',
    brakes: 'hydraulic disc',
    suspension: 'none',
    has_throttle: false,
    has_torque_sensor: true,
    has_app: true,
    has_removable_battery: true,
    key_features: ['Bosch Performance Line motor', 'Enviolo auto-shifting', 'Kiox 300 display', '90-mile range'],
    pros: ['Best-in-class range', 'Auto-shifting is effortless', 'Premium commuter experience', 'Trek dealer everywhere'],
    cons: ['Expensive', 'No throttle', 'Heavy with integrated battery', 'Bosch ecosystem cost'],
    best_for: 'Serious commuters who want the best possible daily driver and have the budget',
    expert_rating: 9.1,
    affiliate_url: 'https://www.trekbikes.com/us/en_US/bikes/electric-bikes/electric-hybrid-bikes/allant/allant-7/',
  },
  {
    brand: 'trek',
    model_name: 'Powerfly 5',
    year: 2025,
    msrp: 3199,
    category: 'mountain',
    ebike_class: 1,
    motor_watts: 250,
    motor_type: 'mid-drive',
    motor_torque_nm: 65,
    battery_wh: 625,
    range_miles_low: 30,
    range_miles_high: 60,
    top_speed_mph: 20,
    charge_time_hours: 5.5,
    weight_lbs: 55,
    max_payload_lbs: 300,
    wheel_size: '29"',
    frame_material: 'aluminum',
    gearing: '12-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'RockShox 100mm',
    has_throttle: false,
    has_torque_sensor: true,
    has_app: true,
    has_removable_battery: false,
    key_features: ['Bosch Performance Line CX', '100mm RockShox fork', '29" trail geometry', '12-speed drivetrain'],
    pros: ['Capable trail performance', 'Trek dealer network', 'Well-sorted geometry', 'Bosch reliability'],
    cons: ['Hardtail (no rear suspension)', 'Non-removable battery', 'Expensive for hardtail', 'Heavy'],
    best_for: 'Trail riders upgrading from analog MTB who want a go-anywhere hardtail eMTB',
    expert_rating: 8.4,
    affiliate_url: 'https://www.trekbikes.com/us/en_US/bikes/electric-bikes/electric-mountain-bikes/powerfly/',
  },

  // ── SPECIALIZED ──────────────────────────────────────────────────────────
  {
    brand: 'specialized',
    model_name: 'Turbo Vado 3.0',
    year: 2025,
    msrp: 3500,
    category: 'commuter',
    ebike_class: 3,
    motor_watts: 250,
    motor_type: 'mid-drive',
    motor_torque_nm: 50,
    battery_wh: 710,
    range_miles_low: 60,
    range_miles_high: 130,
    top_speed_mph: 28,
    charge_time_hours: 6.5,
    weight_lbs: 54,
    max_payload_lbs: 275,
    wheel_size: '700c',
    frame_material: 'aluminum',
    gearing: '10-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'none',
    has_throttle: false,
    has_torque_sensor: true,
    has_app: true,
    has_removable_battery: true,
    key_features: ['MastermindTCU connectivity', 'Future Shock 2.0 stem suspension', 'Up to 130-mile range', 'Specialized app'],
    pros: ['Exceptional range', 'Specialized motor smoothness', 'Future Shock comfort', 'Premium app experience'],
    cons: ['Expensive', 'No throttle', 'Future Shock requires specific stem', 'Specialized dealer required for service'],
    best_for: 'Long-distance commuters and bike-curious professionals who want the best',
    expert_rating: 9.2,
    affiliate_url: 'https://www.specialized.com/us/en/turbo-vado-3-0/p/199044',
  },
  {
    brand: 'specialized',
    model_name: 'Turbo Como 3.0',
    year: 2025,
    msrp: 3250,
    category: 'step-through',
    ebike_class: 3,
    motor_watts: 250,
    motor_type: 'mid-drive',
    motor_torque_nm: 50,
    battery_wh: 710,
    range_miles_low: 60,
    range_miles_high: 130,
    top_speed_mph: 28,
    charge_time_hours: 6.5,
    weight_lbs: 55,
    max_payload_lbs: 275,
    wheel_size: '700c',
    frame_material: 'aluminum',
    gearing: '10-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'none',
    has_throttle: false,
    has_torque_sensor: true,
    has_app: true,
    has_removable_battery: true,
    key_features: ['Step-through frame', 'Future Shock stem suspension', '130-mile range capability', 'MastermindTCU'],
    pros: ['Easy mounting step-through', 'Outstanding range', 'Smooth Specialized motor', 'Premium build quality'],
    cons: ['Very expensive', 'No throttle', 'Service requires Specialized dealer', 'Heavy for step-through'],
    best_for: 'Comfort-focused riders who want top-tier performance in a step-through package',
    expert_rating: 9.0,
    affiliate_url: 'https://www.specialized.com/us/en/turbo-como-3-0/p/199029',
  },
  {
    brand: 'specialized',
    model_name: 'Turbo Levo SL Comp',
    year: 2025,
    msrp: 6000,
    category: 'mountain',
    ebike_class: 1,
    motor_watts: 240,
    motor_type: 'mid-drive',
    motor_torque_nm: 50,
    battery_wh: 320,
    range_miles_low: 25,
    range_miles_high: 65,
    top_speed_mph: 20,
    charge_time_hours: 3.0,
    weight_lbs: 40,
    max_payload_lbs: 265,
    wheel_size: '29"',
    frame_material: 'carbon',
    gearing: '12-speed SRAM',
    brakes: 'hydraulic disc SRAM',
    suspension: 'Fox 140mm',
    has_throttle: false,
    has_torque_sensor: true,
    has_app: true,
    has_removable_battery: false,
    key_features: ['SL motor (lightest eMTB motor)', '40 lb total weight', 'Full carbon frame', 'Fox suspension'],
    pros: ['Closest to analog MTB feel', 'Extremely lightweight for eMTB', 'Outstanding trail performance', 'Premium build'],
    cons: ['Very expensive', 'Small battery (range limited)', 'Carbon requires careful handling', 'Service complexity'],
    best_for: 'Advanced trail riders who want eMTB assistance without sacrificing the feel of a real mountain bike',
    expert_rating: 9.4,
    affiliate_url: 'https://www.specialized.com/us/en/turbo-levo-sl-comp-carbon/p/199102',
  },

  // ── GIANT ────────────────────────────────────────────────────────────────
  {
    brand: 'giant',
    model_name: 'Explore E+ 1',
    year: 2025,
    msrp: 2999,
    category: 'commuter',
    ebike_class: 3,
    motor_watts: 250,
    motor_type: 'mid-drive',
    motor_torque_nm: 60,
    battery_wh: 500,
    range_miles_low: 40,
    range_miles_high: 80,
    top_speed_mph: 28,
    charge_time_hours: 4.5,
    weight_lbs: 48,
    max_payload_lbs: 300,
    wheel_size: '700c',
    frame_material: 'aluminum',
    gearing: '10-speed Shimano Deore',
    brakes: 'hydraulic disc',
    suspension: 'front fork 60mm',
    has_throttle: false,
    has_torque_sensor: true,
    has_app: true,
    has_removable_battery: true,
    key_features: ['SyncDrive Sport motor', 'RideControl Ergo display', 'Integrated light system', 'Full-coverage fenders'],
    pros: ['Giant proprietary motor is excellent', 'Competitive price for specs', 'Giant dealer network', 'Reliable platform'],
    cons: ['No throttle', 'Giant ecosystem lock-in', 'Display is dated', 'Proprietary battery'],
    best_for: 'Commuters who want mid-drive performance at below-Trek pricing with wide dealer coverage',
    expert_rating: 8.8,
    affiliate_url: 'https://www.giant-bicycles.com/us/explore-e-plus-1',
  },
  {
    brand: 'giant',
    model_name: 'Talon E+ 2',
    year: 2025,
    msrp: 2499,
    category: 'mountain',
    ebike_class: 1,
    motor_watts: 250,
    motor_type: 'mid-drive',
    motor_torque_nm: 60,
    battery_wh: 500,
    range_miles_low: 35,
    range_miles_high: 65,
    top_speed_mph: 20,
    charge_time_hours: 4.5,
    weight_lbs: 53,
    max_payload_lbs: 300,
    wheel_size: '29"',
    frame_material: 'aluminum',
    gearing: '10-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'SR Suntour 100mm',
    has_throttle: false,
    has_torque_sensor: true,
    has_app: true,
    has_removable_battery: true,
    key_features: ['29" trail geometry', 'SyncDrive Sport motor', '100mm fork', 'XC/trail capable'],
    pros: ['Affordable eMTB entry point', 'Giant dealer service nationwide', 'Good geometry', 'Reliable motor'],
    cons: ['Suntour fork is entry-level', 'Hardtail only', 'Non-removable battery', 'Not for aggressive trails'],
    best_for: 'Beginners entering eMTB who want a reputable brand with local service at an accessible price',
    expert_rating: 8.3,
    affiliate_url: 'https://www.giant-bicycles.com/us/talon-e-plus-2',
  },
  {
    brand: 'giant',
    model_name: 'FastRoad E+ 1 Pro',
    year: 2025,
    msrp: 3299,
    category: 'road-gravel',
    ebike_class: 3,
    motor_watts: 250,
    motor_type: 'mid-drive',
    motor_torque_nm: 60,
    battery_wh: 500,
    range_miles_low: 45,
    range_miles_high: 85,
    top_speed_mph: 28,
    charge_time_hours: 4.5,
    weight_lbs: 44,
    max_payload_lbs: 265,
    wheel_size: '700c',
    frame_material: 'aluminum',
    gearing: '11-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'none',
    has_throttle: false,
    has_torque_sensor: true,
    has_app: true,
    has_removable_battery: true,
    key_features: ['Flat-bar road geometry', 'Lightweight at 44 lbs', 'SyncDrive Sport', 'Narrow 32mm tires'],
    pros: ['Lightweight road eBike', 'Fast and efficient', 'Giant reliability', 'Clean aesthetics'],
    cons: ['Narrow tires limit terrain', 'No throttle', 'Road-specific (not versatile)', 'No rack/fender mounts'],
    best_for: 'Road cyclists who want electric assist without sacrificing speed and weight',
    expert_rating: 8.6,
    affiliate_url: 'https://www.giant-bicycles.com/us/fastroad-e-plus-1-pro',
  },

  // ── CANNONDALE ───────────────────────────────────────────────────────────
  {
    brand: 'cannondale',
    model_name: 'Adventure Neo 3',
    year: 2025,
    msrp: 2500,
    category: 'commuter',
    ebike_class: 1,
    motor_watts: 250,
    motor_type: 'mid-drive',
    motor_torque_nm: 50,
    battery_wh: 400,
    range_miles_low: 35,
    range_miles_high: 65,
    top_speed_mph: 20,
    charge_time_hours: 4.0,
    weight_lbs: 46,
    max_payload_lbs: 265,
    wheel_size: '700c',
    frame_material: 'aluminum',
    gearing: '9-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'none',
    has_throttle: false,
    has_torque_sensor: true,
    has_app: true,
    has_removable_battery: true,
    key_features: ['Mahle X35+ rear hub motor (hidden)', 'Ghost motor design', 'Clean aesthetic', 'Lightweight'],
    pros: ['Stealthiest motor design available', 'Natural riding feel', 'Lightweight', 'Premium build quality'],
    cons: ['Limited US dealers', 'Class 1 only (20mph)', 'Smaller battery', 'Premium price for wattage'],
    best_for: 'Style-conscious commuters who want an eBike that looks like a regular bike',
    expert_rating: 8.5,
    affiliate_url: 'https://www.cannondale.com/en-us/bikes/urban/adventure-neo/adventure-neo-3',
  },

  // ── GAZELLE ──────────────────────────────────────────────────────────────
  {
    brand: 'gazelle',
    model_name: 'Ultimate C380+ HMB',
    year: 2025,
    msrp: 5499,
    category: 'commuter',
    ebike_class: 3,
    motor_watts: 250,
    motor_type: 'mid-drive',
    motor_torque_nm: 65,
    battery_wh: 500,
    range_miles_low: 50,
    range_miles_high: 100,
    top_speed_mph: 28,
    charge_time_hours: 4.5,
    weight_lbs: 48,
    max_payload_lbs: 265,
    wheel_size: '28"',
    frame_material: 'aluminum',
    gearing: 'Shimano Nexus 380 CVT auto-shift',
    brakes: 'hydraulic disc',
    suspension: 'none',
    has_throttle: false,
    has_torque_sensor: true,
    has_app: true,
    has_removable_battery: true,
    key_features: ['Shimano automatic shifting', 'Bosch Performance Line CX', 'Dutch heritage design', 'Integrated lighting'],
    pros: ['Automatic shifting is effortless', 'Premium Dutch build quality', 'Outstanding comfort', 'Very long range'],
    cons: ['Very expensive', 'Limited US dealers', 'Niche brand in US', 'Heavy for price'],
    best_for: 'Premium buyers who want Dutch commuter cycling culture with automatic everything',
    expert_rating: 9.0,
    affiliate_url: 'https://www.gazellebikes.com/en-us/bikes/ultimate-c380-hmb',
  },

  // ── TERN ─────────────────────────────────────────────────────────────────
  {
    brand: 'tern',
    model_name: 'GSD S10',
    year: 2025,
    msrp: 4599,
    category: 'cargo',
    ebike_class: 1,
    motor_watts: 250,
    motor_type: 'mid-drive',
    motor_torque_nm: 85,
    battery_wh: 500,
    range_miles_low: 30,
    range_miles_high: 75,
    top_speed_mph: 20,
    charge_time_hours: 4.5,
    weight_lbs: 77,
    max_payload_lbs: 440,
    wheel_size: '20"',
    frame_material: 'aluminum',
    gearing: '10-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'rear suspension',
    has_throttle: false,
    has_torque_sensor: true,
    has_app: true,
    has_removable_battery: true,
    key_features: ['Compact footprint (fits elevator)', 'Dual battery option', '440 lb capacity', 'Rear suspension'],
    pros: ['Best compact cargo eBike', 'Fits in standard spaces', 'Excellent rear suspension', 'Massive accessory ecosystem'],
    cons: ['Expensive', 'Heavy', 'No throttle', 'Small wheels affect stability at speed'],
    best_for: 'Urban families who need car-replacement cargo capacity in an elevator-friendly package',
    expert_rating: 9.3,
    affiliate_url: 'https://www.ternbicycles.com/us/bikes/461/gsd-s10',
  },
  {
    brand: 'tern',
    model_name: 'Vektron S10',
    year: 2025,
    msrp: 4199,
    category: 'folding',
    ebike_class: 1,
    motor_watts: 250,
    motor_type: 'mid-drive',
    motor_torque_nm: 50,
    battery_wh: 400,
    range_miles_low: 30,
    range_miles_high: 70,
    top_speed_mph: 20,
    charge_time_hours: 4.0,
    weight_lbs: 46,
    max_payload_lbs: 265,
    wheel_size: '20"',
    frame_material: 'aluminum',
    gearing: '10-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'none',
    has_throttle: false,
    has_torque_sensor: true,
    has_app: true,
    has_removable_battery: true,
    key_features: ['Bosch Active Line Plus', 'Folds to carry-on size', 'Fits in car trunk', 'Premium folding mechanism'],
    pros: ['Best premium folding eBike', 'Bosch motor quality', 'Compact fold', 'Excellent build quality'],
    cons: ['Very expensive for a folder', 'No throttle', 'Class 1 speed', 'Limited US dealers'],
    best_for: 'Professionals who commute by train/bus and need a premium folding eBike',
    expert_rating: 9.1,
    affiliate_url: 'https://www.ternbicycles.com/us/bikes/462/vektron-s10',
  },

  // ── HIMIWAY ──────────────────────────────────────────────────────────────
  {
    brand: 'himiway',
    model_name: 'Cruiser',
    year: 2025,
    msrp: 1699,
    category: 'fat-tire',
    ebike_class: 2,
    motor_watts: 750,
    motor_type: 'rear hub',
    motor_torque_nm: 80,
    battery_wh: 840,
    range_miles_low: 35,
    range_miles_high: 60,
    top_speed_mph: 25,
    charge_time_hours: 6.5,
    weight_lbs: 75,
    max_payload_lbs: 350,
    wheel_size: '26"',
    frame_material: 'aluminum',
    frame_types: ['step-over', 'step-through'],
    gearing: '7-speed Shimano',
    brakes: 'mechanical disc',
    suspension: 'front fork',
    has_throttle: true,
    has_torque_sensor: false,
    has_app: false,
    has_removable_battery: true,
    key_features: ['Large 840Wh battery', 'Moped-style throttle', '750W motor', '4" fat tires'],
    pros: ['Largest battery in class at this price', 'Great all-terrain capability', 'High payload', 'Budget friendly'],
    cons: ['Mechanical disc brakes (not hydraulic)', 'Very heavy', 'No app connectivity', 'No torque sensor'],
    best_for: 'Budget-conscious riders who want maximum battery and motor for all-terrain adventures',
    expert_rating: 8.0,
    affiliate_url: 'https://www.himiwaybike.com/products/himiway-cruiser',
  },
  {
    brand: 'himiway',
    model_name: 'Cobra Pro',
    year: 2025,
    msrp: 2199,
    category: 'mountain',
    ebike_class: 2,
    motor_watts: 1000,
    motor_type: 'rear hub',
    motor_torque_nm: 100,
    battery_wh: 960,
    range_miles_low: 35,
    range_miles_high: 80,
    top_speed_mph: 25,
    charge_time_hours: 7.0,
    weight_lbs: 78,
    max_payload_lbs: 350,
    wheel_size: '26"',
    frame_material: 'aluminum',
    gearing: '9-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'front and rear 80mm',
    has_throttle: true,
    has_torque_sensor: false,
    has_app: false,
    has_removable_battery: true,
    key_features: ['Full suspension', '1000W motor', 'Largest battery in class', 'Aggressive eMTB geometry'],
    pros: ['Extremely powerful for the price', 'Full suspension rare at this price', 'Massive battery', 'Hydraulic brakes'],
    cons: ['Very heavy at 78 lbs', 'Rear hub motor (not mid-drive)', 'No torque sensor', 'Limited trail performance vs. mid-drives'],
    best_for: 'Budget off-road riders who want max power and range for the least money',
    expert_rating: 7.9,
    affiliate_url: 'https://www.himiwaybike.com/products/himiway-cobra-pro',
  },

  // ── RIDE1UP ──────────────────────────────────────────────────────────────
  {
    brand: 'ride1up',
    model_name: 'Prodigy V2',
    year: 2025,
    msrp: 1595,
    category: 'commuter',
    ebike_class: 3,
    motor_watts: 350,
    motor_type: 'mid-drive',
    motor_torque_nm: 60,
    battery_wh: 614,
    range_miles_low: 30,
    range_miles_high: 55,
    top_speed_mph: 28,
    charge_time_hours: 4.0,
    weight_lbs: 38,
    max_payload_lbs: 275,
    wheel_size: '700c',
    frame_material: 'aluminum',
    gearing: '9-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'none',
    has_throttle: true,
    has_torque_sensor: true,
    has_app: false,
    has_removable_battery: true,
    key_features: ['Mid-drive at $1,595', 'Torque sensor', 'Only 38 lbs', 'Class 3 capable'],
    pros: ['Best value mid-drive on market', 'Lightweight', 'Torque sensor standard', 'Hydraulic brakes'],
    cons: ['No app connectivity', 'Smaller brand (fewer local dealers)', 'No suspension', 'Direct-to-consumer only'],
    best_for: 'Tech-savvy riders who want mid-drive performance without the Trek/Specialized price tag',
    expert_rating: 9.1,
    affiliate_url: 'https://ride1up.com/product/prodigy/',
  },
  {
    brand: 'ride1up',
    model_name: '700 Series',
    year: 2025,
    msrp: 1295,
    category: 'commuter',
    ebike_class: 3,
    motor_watts: 500,
    motor_type: 'rear hub',
    motor_torque_nm: 60,
    battery_wh: 614,
    range_miles_low: 30,
    range_miles_high: 55,
    top_speed_mph: 28,
    charge_time_hours: 4.5,
    weight_lbs: 44,
    max_payload_lbs: 275,
    wheel_size: '700c',
    frame_material: 'aluminum',
    frame_types: ['step-over', 'step-through'],
    gearing: '8-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'front fork',
    has_throttle: true,
    has_torque_sensor: false,
    has_app: false,
    has_removable_battery: true,
    key_features: ['Class 3 speed', 'Front suspension', 'Hydraulic disc brakes', 'Integrated lights'],
    pros: ['Class 3 speed at low price', 'Front suspension', 'Complete package', 'Strong value proposition'],
    cons: ['Cadence sensor only', 'DTC means no local dealer service', 'No app', 'Heavier than Prodigy'],
    best_for: 'Speed-focused commuters who want 28mph capability at an accessible budget',
    expert_rating: 8.4,
    affiliate_url: 'https://ride1up.com/product/700series/',
  },

  // ── EVELO ────────────────────────────────────────────────────────────────
  {
    brand: 'evelo',
    model_name: 'Aurora',
    year: 2025,
    msrp: 2999,
    category: 'step-through',
    ebike_class: 2,
    motor_watts: 500,
    motor_type: 'mid-drive',
    motor_torque_nm: 60,
    battery_wh: 576,
    range_miles_low: 30,
    range_miles_high: 60,
    top_speed_mph: 20,
    charge_time_hours: 4.5,
    weight_lbs: 50,
    max_payload_lbs: 275,
    wheel_size: '26"',
    frame_material: 'aluminum',
    gearing: 'Enviolo Trekking stepless',
    brakes: 'hydraulic disc',
    suspension: 'front fork',
    has_throttle: false,
    has_torque_sensor: true,
    has_app: false,
    has_removable_battery: true,
    key_features: ['Enviolo automatic stepless shifting', 'Mid-drive motor', 'Step-through frame', 'Low maintenance drivetrain'],
    pros: ['Automatic shifting is ideal for seniors', 'Mid-drive smooth feel', 'Low step-through', 'Low maintenance'],
    cons: ['Expensive', 'Class 2 only', 'No app', 'Fewer dealers than Trek/Specialized'],
    best_for: 'Seniors and comfort-focused riders who want automatic shifting and easy mounting',
    expert_rating: 8.2,
    affiliate_url: 'https://evelo.com/products/aurora',
  },

  // ── QUIETKAT ─────────────────────────────────────────────────────────────
  {
    brand: 'quietkat',
    model_name: 'Ranger',
    year: 2025,
    msrp: 2499,
    category: 'hunting',
    ebike_class: 2,
    motor_watts: 750,
    motor_type: 'rear hub',
    motor_torque_nm: 80,
    battery_wh: 614,
    range_miles_low: 20,
    range_miles_high: 45,
    top_speed_mph: 20,
    charge_time_hours: 5.0,
    weight_lbs: 65,
    max_payload_lbs: 325,
    wheel_size: '26"',
    frame_material: 'aluminum',
    gearing: '7-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'front fork',
    has_throttle: true,
    has_torque_sensor: false,
    has_app: true,
    has_removable_battery: true,
    key_features: ['Camo finish options', 'Ultra-quiet motor', 'All-terrain 4" tires', 'Cargo rack included'],
    pros: ['Quietest motor in hunting segment', 'Purpose-built for hunting', 'App connectivity', 'Strong carrying capacity'],
    cons: ['Expensive for specs', 'Cadence sensor only', 'Niche use case', 'Heavy'],
    best_for: 'Hunters and outdoor enthusiasts who need silent, powerful trail transportation',
    expert_rating: 8.5,
    affiliate_url: 'https://quietkat.com/products/ranger',
  },
  {
    brand: 'quietkat',
    model_name: 'Apex',
    year: 2025,
    msrp: 3999,
    category: 'hunting',
    ebike_class: 2,
    motor_watts: 1000,
    motor_type: 'mid-drive',
    motor_torque_nm: 120,
    battery_wh: 960,
    range_miles_low: 25,
    range_miles_high: 55,
    top_speed_mph: 20,
    charge_time_hours: 7.0,
    weight_lbs: 78,
    max_payload_lbs: 325,
    wheel_size: '26"',
    frame_material: 'aluminum',
    gearing: '9-speed Shimano',
    brakes: 'hydraulic disc',
    suspension: 'front and rear',
    has_throttle: true,
    has_torque_sensor: false,
    has_app: true,
    has_removable_battery: true,
    key_features: ['1000W mid-drive', 'Full suspension', 'Largest battery in hunting category', 'Air-ride saddle'],
    pros: ['Most capable hunting eBike available', 'Mid-drive for hill climbing', 'Full suspension for rough terrain', 'Huge battery'],
    cons: ['Very expensive', 'Very heavy', 'Overkill for casual use', 'Limited to hunting niche'],
    best_for: 'Serious hunters and backcountry users who need maximum power and range in rugged terrain',
    expert_rating: 8.8,
    affiliate_url: 'https://quietkat.com/products/apex',
  },
];

// ── Insert bikes ──────────────────────────────────────────────────────────────

console.log(`Seeding ${bikes.length} bikes across ${Object.keys(BRANDS).length} brands...\n`);
let inserted = 0;
let skipped = 0;
let errors = 0;

for (const bike of bikes) {
  const brandId = BRANDS[bike.brand];
  if (!brandId) {
    console.error(`✗ Brand not found: ${bike.brand}`);
    errors++;
    continue;
  }

  const slug = `${bike.brand}-${toSlug(bike.model_name)}`;

  try {
    await sql`
      INSERT INTO bikes (
        brand_id, model_name, slug, year, msrp, category, ebike_class,
        motor_watts, motor_type, motor_torque_nm,
        battery_wh, range_miles_low, range_miles_high,
        top_speed_mph, charge_time_hours, weight_lbs, max_payload_lbs,
        wheel_size, frame_material, frame_types, gearing, brakes, suspension,
        has_throttle, has_torque_sensor, has_app, has_removable_battery,
        key_features, pros, cons, best_for, expert_rating, affiliate_url,
        is_active
      ) VALUES (
        ${brandId}, ${bike.model_name}, ${slug}, ${bike.year ?? 2025}, ${bike.msrp},
        ${bike.category}, ${bike.ebike_class ?? null},
        ${bike.motor_watts ?? null}, ${bike.motor_type ?? null}, ${bike.motor_torque_nm ?? null},
        ${bike.battery_wh ?? null}, ${bike.range_miles_low ?? null}, ${bike.range_miles_high ?? null},
        ${bike.top_speed_mph ?? null}, ${bike.charge_time_hours ?? null},
        ${bike.weight_lbs ?? null}, ${bike.max_payload_lbs ?? null},
        ${bike.wheel_size ?? null}, ${bike.frame_material ?? null},
        ${bike.frame_types ? sql.array(bike.frame_types) : null},
        ${bike.gearing ?? null}, ${bike.brakes ?? null}, ${bike.suspension ?? null},
        ${bike.has_throttle ?? false}, ${bike.has_torque_sensor ?? false},
        ${bike.has_app ?? false}, ${bike.has_removable_battery ?? true},
        ${sql.array(bike.key_features ?? [])},
        ${sql.array(bike.pros ?? [])},
        ${sql.array(bike.cons ?? [])},
        ${bike.best_for ?? null}, ${bike.expert_rating ?? null},
        ${bike.affiliate_url ?? null},
        true
      )
      ON CONFLICT (slug) DO UPDATE SET
        msrp = EXCLUDED.msrp,
        expert_rating = EXCLUDED.expert_rating,
        key_features = EXCLUDED.key_features,
        pros = EXCLUDED.pros,
        cons = EXCLUDED.cons,
        updated_at = NOW()
    `;
    console.log(`  ✓ ${bike.brand} — ${bike.model_name}`);
    inserted++;
  } catch (err) {
    console.error(`  ✗ ${bike.brand} — ${bike.model_name}: ${err.message}`);
    errors++;
  }
}

console.log(`\nResult: ${inserted} inserted/updated, ${skipped} skipped, ${errors} errors`);
await sql.end();
